/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinanciero.Venta;

import DAO.DAO_Productos;
import Tablas.tblProductoSeleccionado2;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
import modelos.Producto;
import proyectofinanciero.Empleados;
import proyectofinanciero.Menu;

/**
 *
 * @author Josue
 */
public class SelectProducto extends javax.swing.JFrame {

    /**
     * Creates new form SelectProducto
     */
    tblProductoSeleccionado2 modelo;
    Producto producto;
    boolean cFre = false;
    ArrayList<Producto> prodSeleccionado;
    double total;

    public SelectProducto() {
        initComponents();
        prodSeleccionado = new ArrayList<>();
        modelo = new tblProductoSeleccionado2();
        tblProductos.setModel(modelo);
        tblProductos.setAutoCreateRowSorter(true);
    }

    private void filtro(String consulta, JTable jtableBuscar) {
        modelo = (tblProductoSeleccionado2) jtableBuscar.getModel();
        TableRowSorter<tblProductoSeleccionado2> tr = new TableRowSorter<>(modelo);
        jtableBuscar.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(consulta));
    }

    public SelectProducto(boolean client) {
        initComponents();
        prodSeleccionado = new ArrayList<>();
        modelo = new tblProductoSeleccionado2();
        tblProductos.setModel(modelo);
        tblProductos.setAutoCreateRowSorter(true);
        cFre = client;
        lbTotal.setVisible(false);
        lblTotal.setVisible(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        bxMeses = new javax.swing.JComboBox<>();
        lblM = new javax.swing.JLabel();
        lblCuo = new javax.swing.JLabel();
        lblPri = new javax.swing.JLabel();
        txtCuota = new javax.swing.JTextField();
        txtPrima = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        lblDesc = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtCodig = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        spCant = new javax.swing.JSpinner();
        cbContado = new javax.swing.JCheckBox();
        lbTotal = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("SELECCIÓN DE PRODUCTO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(105, 105, 105))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "COD.", "PRODUCTO", "STOCK", "PRECIO U."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProductos);

        bxMeses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "12 Meses", "24 Meses", "36 Meses" }));
        bxMeses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bxMesesActionPerformed(evt);
            }
        });

        lblM.setText("Meses");

        lblCuo.setText("Cuota");

        lblPri.setText("Prima");

        txtCuota.setEditable(false);
        txtCuota.setText("$0.00");

        txtPrima.setEditable(false);
        txtPrima.setText("$00.00");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel5.setText("Descuento cliente frecuente 10% $");

        lblDesc.setText("00.00");

        btnAgregar.setBackground(new java.awt.Color(255, 153, 0));
        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("BUSQUEDA");

        txtCodig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigActionPerformed(evt);
            }
        });
        txtCodig.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigKeyTyped(evt);
            }
        });

        jLabel2.setText("Cant.");

        spCant.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        spCant.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spCantStateChanged(evt);
            }
        });

        cbContado.setText("Contado");
        cbContado.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbContadoStateChanged(evt);
            }
        });
        cbContado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbContadoActionPerformed(evt);
            }
        });

        lbTotal.setText("TOTAL $");

        lblTotal.setText("00.00");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblCuo)
                                    .addComponent(lblM)
                                    .addComponent(lblPri))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtPrima, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCuota, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bxMeses, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(spCant, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addComponent(cbContado)
                                .addContainerGap())
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCodig, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblDesc)
                    .addComponent(lbTotal)
                    .addComponent(lblTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(cbContado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 8, Short.MAX_VALUE))
                            .addComponent(jSeparator1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblM)
                            .addComponent(bxMeses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCuo)
                            .addComponent(txtCuota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPri)
                            .addComponent(txtPrima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductosMouseClicked
        // TODO add your handling code here:
        int x = tblProductos.getSelectedRow();
        if (cFre) {
            lblDesc.setText(String.valueOf(Double.parseDouble(tblProductos.getValueAt(x, 3).toString()) * 0.10));
            Double precioU = Double.parseDouble(tblProductos.getValueAt(x, 3).toString());
            lblTotal.setText(String.format("%3.2f", precioU - Double.parseDouble(lblDesc.getText())));
        }
        if (bxMeses.getSelectedIndex() > 0) {
            Double precioU = Double.parseDouble(tblProductos.getValueAt(x, 3).toString());
            double total;
            switch (bxMeses.getSelectedIndex()) {
                case 1:
                    total = (((precioU * 30) / 100) + precioU) - Double.parseDouble(lblDesc.getText());
                    txtCuota.setText(String.format("%3.2f", (total / 12) * Integer.parseInt(spCant.getValue().toString())));
                    txtPrima.setText(String.format("%3.2f", ((total * 10) / 100) * Integer.parseInt(spCant.getValue().toString())));
                    break;
                case 2:
                    total = ((precioU * 50) / 100) + precioU;
                    txtCuota.setText(String.format("%3.2f", (total / 24) * Integer.parseInt(spCant.getValue().toString())));
                    txtPrima.setText(String.format("%3.2f", ((total * 11) / 100) * Integer.parseInt(spCant.getValue().toString())));
                    break;
                case 3:
                    total = ((precioU * 75) / 100) + precioU;
                    txtCuota.setText(String.format("%3.2f", (total / 36) * Integer.parseInt(spCant.getValue().toString())));
                    txtPrima.setText(String.format("%3.2f", ((total * 12) / 100) * Integer.parseInt(spCant.getValue().toString())));
                    break;
            }
        } else {
            txtCuota.setText("0.00");
            txtPrima.setText("0.00");
        }
    }//GEN-LAST:event_tblProductosMouseClicked

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        int x = tblProductos.getSelectedRow();
        int meses= 36;
        if (x == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un producto");
        } else {
            if (cbContado.isSelected()) {
                try {
                    int idProd = Integer.parseInt(tblProductos.getValueAt(x, 0).toString());
                    if (busqProd(idProd)) {
                        if (bxMeses.getSelectedIndex() == 1) {
                            meses = 12;
                        } else {
                            meses = 24;
                        }
                        prodSeleccionado.add(new Producto(producto.getIdProd(), producto.getNombre(), Integer.parseInt(spCant.getValue().toString()), Double.parseDouble(tblProductos.getValueAt(x, 3).toString()), Double.parseDouble(lblDesc.getText())));
                        Menu.v.actualizarProduct();
                        Menu.v.blocCliente();
                        dispose();
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Empleados.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else if (bxMeses.getSelectedIndex() > 0) {
                try {
                    int idProd = Integer.parseInt(tblProductos.getValueAt(x, 0).toString());
                    if (busqProd(idProd)) {
                        int mes;
                        if (cbContado.isSelected()) {
                            switch (bxMeses.getSelectedIndex()) {
                                case 1:
                                    mes = 12;
                                    break;
                                case 2:
                                    mes = 24;
                                    break;
                                default:
                                    mes = 36;
                                    break;
                            }
                            prodSeleccionado.add(new Producto(producto.getIdProd(), producto.getNombre(), Integer.parseInt(spCant.getValue().toString()), Double.parseDouble(tblProductos.getValueAt(x, 3).toString()), Double.parseDouble(lblDesc.getText()), Double.parseDouble(txtCuota.getText()), Double.parseDouble(txtPrima.getText()), mes));

                        } else {
                            switch (bxMeses.getSelectedIndex()) {
                                case 1:
                                    mes = 12;
                                    break;
                                case 2:
                                    mes = 24;
                                    break;
                                default:
                                    mes = 36;
                                    break;
                            }
                            prodSeleccionado.add(new Producto(producto.getIdProd(), producto.getNombre(), Integer.parseInt(spCant.getValue().toString()), total, Double.parseDouble(lblDesc.getText()), Double.parseDouble(txtCuota.getText()), Double.parseDouble(txtPrima.getText()), mes));
                        }
                        Menu.v.actualizarProduct();
                        Menu.v.blocCliente();
                        dispose();
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Empleados.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Seleccione meses plazo a pagar.");
            }

        }

    }//GEN-LAST:event_btnAgregarActionPerformed

    private boolean busqProd(int dui) throws SQLException {
        DAO_Productos daoEm = new DAO_Productos();
        for (Producto x : daoEm.getProductos()) {
            if (dui == 0 ? x.getIdProd() == 0 : dui == (x.getIdProd())) {
                producto = x;
                return true;
            }
        }
        return false;
    }

    private void txtCodigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigActionPerformed

    private void txtCodigKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigKeyTyped

    private void txtCodigKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigKeyReleased
        // TODO add your handling code here:
        filtro(txtCodig.getText().toUpperCase(), tblProductos);
    }//GEN-LAST:event_txtCodigKeyReleased

    private void bxMesesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bxMesesActionPerformed
        // TODO add your handling code here:
        EstabCuota();
    }//GEN-LAST:event_bxMesesActionPerformed

    private void EstabCuota() {
        int x = tblProductos.getSelectedRow();
        if (bxMeses.getSelectedIndex() > 0) {
            Double precioU = Double.parseDouble(tblProductos.getValueAt(x, 3).toString());
            switch (bxMeses.getSelectedIndex()) {
                case 1:
                    if (cFre) {
                        lblDesc.setText(String.format("%3.2f", (((precioU * 30) / 100) + precioU) * 0.1));
                    }
                    total = (((precioU * 30) / 100) + precioU) - Double.parseDouble(lblDesc.getText());
                    txtCuota.setText(String.format("%3.2f", (total / 12) * Integer.parseInt(spCant.getValue().toString())));
                    txtPrima.setText(String.format("%3.2f", ((total * 10) / 100) * Integer.parseInt(spCant.getValue().toString())));
                    break;
                case 2:
                    if (cFre) {
                        lblDesc.setText(String.format("%3.2f", (((precioU * 50) / 100) + precioU) * 0.1));
                    }
                    total = ((precioU * 50) / 100) + precioU;
                    txtCuota.setText(String.format("%3.2f", (total / 24) * Integer.parseInt(spCant.getValue().toString())));
                    txtPrima.setText(String.format("%3.2f", ((total * 11) / 100) * Integer.parseInt(spCant.getValue().toString())));
                    break;
                case 3:
                    if (cFre) {
                        lblDesc.setText(String.format("%3.2f", (((precioU * 75) / 100) + precioU) * 0.1));
                    }
                    total = ((precioU * 75) / 100) + precioU;
                    txtCuota.setText(String.format("%3.2f", (total / 36) * Integer.parseInt(spCant.getValue().toString())));
                    txtPrima.setText(String.format("%3.2f", ((total * 12) / 100) * Integer.parseInt(spCant.getValue().toString())));
                    break;
            }
        } else {
            txtCuota.setText("0.00");
            txtPrima.setText("0.00");
            lblDesc.setText("0.00");
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void spCantStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spCantStateChanged
        EstabCuota();
    }//GEN-LAST:event_spCantStateChanged

    private void cbContadoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbContadoStateChanged

    }//GEN-LAST:event_cbContadoStateChanged

    private void cbContadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbContadoActionPerformed
        // TODO add your handling code here:
        if (cbContado.isSelected()) {
            bxMeses.setEnabled(false);
            txtCuota.setEnabled(false);
            txtPrima.setEnabled(false);

            lbTotal.setVisible(true);
            lblTotal.setVisible(true);

            int x = tblProductos.getSelectedRow();
            Double precioU = Double.parseDouble(tblProductos.getValueAt(x, 3).toString());
            lblTotal.setText(String.format("%3.2f", precioU - Double.parseDouble(lblDesc.getText())));
            if (cFre) {
                lblDesc.setText(String.valueOf((Double.parseDouble(tblProductos.getValueAt(x, 3).toString()) * 0.10) * Integer.parseInt(spCant.getValue().toString())));
            }
        } else {
            bxMeses.setEnabled(true);
            txtCuota.setEnabled(true);
            txtPrima.setEnabled(true);
            lbTotal.setVisible(false);
            lblTotal.setVisible(false);
        }
    }//GEN-LAST:event_cbContadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JComboBox<String> bxMeses;
    private javax.swing.JCheckBox cbContado;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JLabel lblCuo;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblM;
    private javax.swing.JLabel lblPri;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JSpinner spCant;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtCodig;
    private javax.swing.JTextField txtCuota;
    private javax.swing.JTextField txtPrima;
    // End of variables declaration//GEN-END:variables
}
