/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinanciero.Venta;

import proyectofinanciero.*;
import DAO.DAO_Productos;
import Tablas.tablaProductos;
import Tablas.tblProductoSeleccionado;
import Tablas.tblProductosVenta;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelos.MarcaV;
import modelos.Producto;
import modelos.Venta;

/**
 *
 * @author Josue
 */
public class TblProducto extends javax.swing.JFrame {

    /**
     * Creates new form TblProducto
     */
    tblProductosVenta tablaProd;
    ArrayList<Venta> prodAVender;
    ArrayList<Producto> prodSeleccionado;
    Producto productoS;
    MarcaV m;
    tblProductoSeleccionado modeloTabla;
    Venta venta;
    Double total;
    Integer meses;

    public TblProducto() {
        initComponents();
        tablaProd = new tblProductosVenta();
        tblProductos.setModel(tablaProd);
        prodAVender = new ArrayList<>();
        prodSeleccionado = new ArrayList<>();
        productoS = new Producto();
        m = new MarcaV();
        meses = 0;
        btnContado.setSelected(true);
        hideComp();
    }

    private void hideComp() {
        lblCuota.setVisible(false);
        lblM.setVisible(false);
        bxMeses.setVisible(false);
        txtCuota.setVisible(false);
        lblT.setVisible(true);
        lbltotal.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        spCantidad = new javax.swing.JSpinner();
        btnAgg = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnCredito = new javax.swing.JRadioButton();
        btnContado = new javax.swing.JRadioButton();
        bxMeses = new javax.swing.JComboBox<>();
        lblM = new javax.swing.JLabel();
        lblCuota = new javax.swing.JLabel();
        lblT = new javax.swing.JLabel();
        lbltotal = new javax.swing.JLabel();
        txtCuota = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("PRODUCTOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(219, 219, 219))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProductos);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Cantidad"));

        spCantidad.setModel(new javax.swing.SpinnerNumberModel(1, 0, null, 1));
        spCantidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spCantidadStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(spCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spCantidad)
        );

        btnAgg.setText("Agregar");
        btnAgg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAggActionPerformed(evt);
            }
        });

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancelar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnCredito);
        btnCredito.setText("Credito");
        btnCredito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCreditoMouseClicked(evt);
            }
        });

        buttonGroup1.add(btnContado);
        btnContado.setText("Contado");
        btnContado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnContadoMouseClicked(evt);
            }
        });

        bxMeses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "12 Meses", "24 Meses", "36 Meses" }));
        bxMeses.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                bxMesesItemStateChanged(evt);
            }
        });
        bxMeses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bxMesesActionPerformed(evt);
            }
        });

        lblM.setText("Meses");

        lblCuota.setText("Cuota");

        lblT.setText("Total : ");

        txtCuota.setText("$0.00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCredito)
                            .addComponent(btnContado))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblM)
                            .addComponent(lblCuota))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCuota)
                            .addComponent(bxMeses, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbltotal)
                            .addComponent(lblT))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                        .addComponent(btnAgg, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(btnCancel))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCredito)
                            .addComponent(lblM)
                            .addComponent(bxMeses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblT))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnContado)
                            .addComponent(lblCuota)
                            .addComponent(lbltotal)
                            .addComponent(txtCuota)))
                    .addComponent(btnAgg, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAggActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAggActionPerformed
        // TODO add your handling code here:
        int x = tblProductos.getSelectedRow();
        if (x == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un producto");
        } else {
            int cantidad = (int) spCantidad.getValue();
            String marca = tblProductos.getValueAt(x, 3).toString();
            m.setMarca(marca);
            productoS.setMarca(m);
            int idProd = (int) tblProductos.getValueAt(x, 0);
            String prod = tblProductos.getValueAt(x, 1).toString();
            productoS.setId(idProd);
            productoS.setNombre(prod);
            Double subtotal;
            if (btnCredito.isSelected()) {
                if (bxMeses.getSelectedIndex() > 0) {
                    int mes = bxMeses.getSelectedIndex();
                    double cuota = Cuota(mes);
                    txtCuota.setText(String.valueOf(cuota));
                    subtotal = total;
                    prodAVender.add(new Venta(productoS, cantidad, cuota, subtotal, meses));
                } else {
                    JOptionPane.showMessageDialog(this, "Seleccione cantidad de meses");
                }

            } else {
                double precio = Double.parseDouble(tblProductos.getValueAt(x, 5).toString());
                total = (precio) * cantidad;
                prodAVender.add(new Venta(productoS, cantidad, 0, total));

            }

//        double total = Double.parseDouble(txtTotal.getText());
//            prodAComprar.add(new Producto(id, nombre, cantidad, Double.parseDouble(String.format("%.2f", total))));
            Menu.v.ActualizarTabla();
            dispose();
        }
    }//GEN-LAST:event_btnAggActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String SearchP = txtSearch.getText();
        if (!"".equals(SearchP)) {
            try {
                if (busqPF(SearchP)) {
                    uTabla();
                }
            } catch (SQLException ex) {
                Logger.getLogger(TblProducto.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Campo Vacio");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        tablaProd = new tblProductosVenta();
        tblProductos.setModel(tablaProd);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void bxMesesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bxMesesActionPerformed

    }//GEN-LAST:event_bxMesesActionPerformed

    private void btnCreditoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreditoMouseClicked
        // TODO add your handling code here:
        lblCuota.setVisible(true);
        lblM.setVisible(true);
        bxMeses.setVisible(true);
        txtCuota.setVisible(true);
        lblT.setVisible(false);
        lbltotal.setVisible(false);
    }//GEN-LAST:event_btnCreditoMouseClicked

    private void btnContadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContadoMouseClicked
        // TODO add your handling code here:
        uTotal();
        hideComp();
        meses = 0;
    }//GEN-LAST:event_btnContadoMouseClicked

    private void spCantidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spCantidadStateChanged
        // TODO add your handling code here:
        if (btnCredito.isSelected()) {
            uCuota();
        } else {
            uTotal();
        }
        int x = tblProductos.getSelectedRow();
        int stock = (int) tblProductos.getValueAt(x, 4);
        int c = (int) spCantidad.getValue();
        if (stock < c) {
            JOptionPane.showMessageDialog(this, "No hay unidades suficientes de este producto en stock");
            btnAgg.setEnabled(false);
        } else {
            btnAgg.setEnabled(true);
        }
    }//GEN-LAST:event_spCantidadStateChanged

    private void tblProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductosMouseClicked
        // TODO add your handling code here:
        if (btnCredito.isSelected()) {
            uCuota();
        } else {
            uTotal();
        }
        int x = tblProductos.getSelectedRow();
        int stock = (int) tblProductos.getValueAt(x, 4);
        if (stock == 0) {
            JOptionPane.showMessageDialog(this, "No hay unidades de este producto en stock");
            btnAgg.setEnabled(false);
        } else {
            btnAgg.setEnabled(true);
        }
    }//GEN-LAST:event_tblProductosMouseClicked

    private void bxMesesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_bxMesesItemStateChanged
        // TODO add your handling code here:
        uCuota();
    }//GEN-LAST:event_bxMesesItemStateChanged
    private void uCuota() {
        int s = bxMeses.getSelectedIndex();
        if (s > 0) {
            int x = tblProductos.getSelectedRow();
            if (x == -1) {
                JOptionPane.showMessageDialog(this, "Seleccione un producto");
            } else {
                double cuota = Cuota(s);
                txtCuota.setText("$" + String.format("%.2f", cuota));
            }
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un plan de pago");
        }
    }

    private void uTotal() {
        int x = tblProductos.getSelectedRow();
        if (x == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un Producto");
        } else {
            double precio = Double.parseDouble(tblProductos.getValueAt(x, 5).toString());
            int cantidad = (int) spCantidad.getValue();
            total = (precio) * cantidad;
            lbltotal.setText(String.valueOf(total));
        }
    }

    private boolean busqPF(String nombre) throws SQLException {
        DAO_Productos daoP = new DAO_Productos();
        for (Producto x : daoP.getProductosF(nombre)) {
            prodSeleccionado.add(x);
        }
        if (!prodSeleccionado.isEmpty()) {
            return true;
        }
        return false;
    }

    private void uTabla() {
        tablaProd = new tblProductosVenta(prodSeleccionado);
        tblProductos.setModel(tablaProd);
        tablaProd.fireTableDataChanged();
        prodSeleccionado = new ArrayList<>();
    }

    private Double Cuota(Integer m) {
        int x = tblProductos.getSelectedRow();
        int cantidad = (int) spCantidad.getValue();
        double precio = Double.parseDouble(tblProductos.getValueAt(x, 5).toString());
        switch (m) {
            case 1:
                meses = 12;
                total = (((precio * 30) / 100) + precio) * cantidad;
                return total / 12;
            case 2:
                meses = 24;
                total = (((precio * 60) / 100) + precio) * cantidad;
                return total / 24;
            case 3:
                meses = 36;
                total = (((precio * 90) / 100) + precio) * cantidad;
                return total / 36;
        }
        return 0.0;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgg;
    private javax.swing.JButton btnCancel;
    private javax.swing.JRadioButton btnContado;
    private javax.swing.JRadioButton btnCredito;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> bxMeses;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCuota;
    private javax.swing.JLabel lblM;
    private javax.swing.JLabel lblT;
    private javax.swing.JLabel lbltotal;
    private javax.swing.JSpinner spCantidad;
    private javax.swing.JTable tblProductos;
    private javax.swing.JLabel txtCuota;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

}
